name: "Tests"

on:
  push:
    branches:
      - "main"
      - "master"
      - "dev/*"
  pull_request:

jobs:
  lab-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: "Check out source tree"
        uses: actions/checkout@v3

      - name: "Start containers"
        run: |
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml up --build -d
          sleep 10

      - name: "Show logs"
        run: |
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml logs as150_router
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml logs as151_router
