name: "Tests"

on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:

jobs:
  snmp-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: "Check out source tree"
        uses: actions/checkout@v3

      - name: "Configure sysctl"
        run: |
          sudo sysctl net.ipv4.conf.all.proxy_arp=1
          sudo sysctl net.ipv4.ip_forward=1
          sudo sysctl net.ipv4.conf.all.forwarding=1
          sudo iptables -P FORWARD ACCEPT

      - name: "Re-load dockerd with IPv6 enabled"
        run: |
          cat /etc/docker/daemon.json | perl -pe 's| }|, "ipv6": true, "fixed-cidr-v6": "2001:db8:1::/64" }|' | sudo tee /etc/docker/daemon.json > /dev/null; sudo systemctl restart docker; sleep 10

      - name: "Start containers"
        run: |
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml up -d
          sleep 10

      - name: "Sanity ping"
        run: |
          ping -c 2 10.9.0.5
          ping6 -c 2 2001:db8:1:1::5

      - name: "Inspect networks"
        run: |
          docker network inspect bridge
          docker network inspect net-snmpd

      - name: "Show interfaces"
        run: |
          ip -4 addr
          ip -6 addr

      - name: "Show routes"
        run: |
          ip -4 route
          ip -6 route

      - name: "Show neighbors"
        run: |
          ip -4 neigh
          ip -6 neigh

      - name: "Show links"
        run: |
          ip -4 link
          ip -6 link

      - name: "Sanity nmap scan"
        run: |
          sudo apt-get install nmap
          sudo nmap --iflist
          sudo nmap -sU -p 161 --disable-arp-ping -n --reason -vv 10.9.0.5-10.9.0.8 --packet-trace -d --traceroute -Pn
          sudo nmap -sU -p 161 --disable-arp-ping -n --reason -vv -6 2001:db8:1:1::5-2001:db8:1:1::8 --packet-trace -d --traceroute -Pn
