name: "Tests"

on:
  push:
    branches:
      - "main"
      - "master"
      - "dev/*"
  pull_request:

jobs:
  snmp-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: "Check out source tree"
        uses: actions/checkout@v3

      #- name: "Configure sysctl"
      #  run: |
      #    sudo sysctl net.ipv4.conf.all.proxy_arp=1
      #    sudo sysctl net.ipv4.ip_forward=1
      #    sudo sysctl net.ipv4.conf.all.forwarding=1
      #    sudo iptables -P FORWARD ACCEPT

      - name: "Re-load dockerd with IPv6 enabled"
        run: |
          cat /etc/docker/daemon.json | perl -pe 's| }|, "ipv6": true, "fixed-cidr-v6": "2001:db8:1::/64" }|' | sudo tee /etc/docker/daemon.json > /dev/null; sudo systemctl restart docker; sleep 10

      - name: "Start containers"
        run: |
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml up -d
          sleep 10

      - name: "Delete default route on router"
        run: |
          docker exec bird-router ip route del default

      - name: "Sanity ping"
        run: |
          ping -c 2 10.9.0.5 # snmpd-01 ipv4
          ping6 -c 2 2001:db8:1:1::5 # snmpd-01 ipv6
          #sudo tcpdump -i any -w ping-snmpd-01.pcap & ping -c 5 10.9.0.5 ; sudo kill $!
          sudo tcpdump -i any -w ping-snmpd-01.pcap & ping -c 2 10.9.0.5 ; sleep 1; sudo killall -e tcpdump
          tcpdump -r ping-snmpd-01.pcap -e -vv -XX icmp || true

      - name: "Inspect networks"
        run: |
          docker network inspect bridge
          docker network inspect net-snmpd

      - name: "Show interfaces (1/2)"
        run: |
          ip -4 addr
          ip -6 addr

      - name: "Show interfaces (2/2)"
        run: |
          ifconfig

      - name: "Show routes (1/2)"
        run: |
          ip -4 route
          ip -6 route

      - name: "Show routes (2/2)"
        run: |
          route -n

      - name: "Show neighbors"
        run: |
          ip -4 neigh
          ip -6 neigh

      - name: "Show links"
        run: |
          ip -4 link
          ip -6 link

      - name: "Sanity nmap scan"
        run: |
          sudo apt-get install -y nmap
          sudo nmap --iflist
          sudo nmap -sU -p 161 --disable-arp-ping -n --reason -vv 10.9.0.5 10.9.0.6 --packet-trace -d --traceroute -Pn
          sudo nmap -sU -p 161 --disable-arp-ping -n --reason -vv -6 2001:db8:1:1::5 2001:db8:1:1::6 --packet-trace -d --traceroute -Pn

      - name: "Build masscan"
        run: |
          make -C masscan -j3
          sudo make -C masscan install

      - name: "Sanity masscan scan"
        run: |
          sudo masscan -pU:161 \
               --banners \
               --rate 400 \
               --wait 2 \
               -vvv \
               10.9.0.5 \
               #
          sudo masscan -pU:161 \
               --banners \
               --rate 400 \
               --wait 2 \
               -vvv \
               10.9.0.5 \
               -i br-snmpd --router-mac 02:42:0a:09:00:05
          sudo masscan -pU:161 \
               --banners \
               --rate 400 \
               --wait 2 \
               -vvv \
               10.9.0.5 \
               -i br-snmpd \
               & sleep 30 ; sudo kill $!

      - name: "Show logs"
        run: |
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml logs snmpd-01
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml logs router
