name: "Tests"

on:
  push:
    branches:
      - "main"
      - "master"
      - "dev/*"
  pull_request:

jobs:
  lab-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: "Check out source tree"
        uses: actions/checkout@v3

      - name: "Re-load dockerd with IPv6 enabled"
        run: |
          cat /etc/docker/daemon.json | perl -pe 's| }|, "ipv6": true, "fixed-cidr-v6": "2001:db8:1::/64" }|' | sudo tee /etc/docker/daemon.json > /dev/null; sudo systemctl restart docker; sleep 10


      - name: "Start containers"
        run: |
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml build
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml up -d
          sleep 10

      - name: "Show logs"
        run: |
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml logs as150_router
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml logs as151_router

      - name: "Inspect networks"
        run: |
          docker network inspect seed-ix100-net || true
          docker network inspect seed-as150-net || true
          docker network inspect seed-as151-net || true

      - name: "Inspect as150-router-10.150.0.254"
        run: |
          docker exec as150-router-10.150.0.254 ifconfig || true
          docker exec as150-router-10.150.0.254 route -n || true

      - name: "Sanity ping from as150-host-10.150.0.71"
        run: |
          docker exec as150-host-10.150.0.71 ifconfig || true
          docker exec as150-host-10.150.0.71 route -n || true
          docker exec as150-host-10.150.0.71 ping -c 2 101.150.0.254 || true
          docker exec as150-host-10.150.0.71 ping -c 2 101.151.0.71 || true
