name: "Tests"

on:
  push:
    branches:
      - "main"
      - "master"
      - "dev/*"
  pull_request:

jobs:
  lab-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: "Check out source tree"
        uses: actions/checkout@v3

      - name: "Start containers"
        run: |
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml up --build -d
          sleep 10

      - name: "Show logs"
        run: |
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml logs as150_router
          docker-compose -f $(pwd)/tests/resources/docker-compose.yml logs as151_router

      - name: "Inspect as150-router-10.150.0.254"
        run: |
          docker exec as150-router-10.150.0.254 ifconfig || true
          docker exec as150-router-10.150.0.254 route -n || true

      - name: "Sanity ping from as150-host-10.150.0.71"
        run: |
          docker exec as150-host-10.150.0.71 ifconfig || true
          docker exec as150-host-10.150.0.71 route -n || true
          docker exec as150-host-10.150.0.71 ping -c 2 101.151.0.71 || true
